GET http://localhost:3000/api/user

###

POST http://localhost:3000/api/user/add
Content-Type: application/json

{
    "name": "Adarsh",
    "email": "adarsh@gmail.com",
    "age": 23,
    "password": "7890"
}

###

PATCH http://localhost:3000/api/user/update/6a252f8cef406a10537757d3
Content-Type: application/json

{
    "name": "Updated Akash"
}

###

DELETE http://localhost:3000/api/user/delete/6a252f8cef406a10537757d3